# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6707189c25e41c08024c15e8f2cb6520"
name = "Sellcross"
handle = "sellcross"
application_url = "https://3dcf-2401-4900-1f37-cbfd-1d35-c7a8-c9fb-a870.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "delta-store-test01.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_metaobjects, write_metaobjects,read_metaobject_definitions ,write_metaobject_definitions, read_metaobjects, unauthenticated_read_metaobjects,  unauthenticated_read_product_listings, write_discounts, unauthenticated_read_customers, write_discounts_allocator_functions"

[auth]
redirect_urls = [
  "https://3dcf-2401-4900-1f37-cbfd-1d35-c7a8-c9fb-a870.ngrok-free.app/auth/callback",
  "https://3dcf-2401-4900-1f37-cbfd-1d35-c7a8-c9fb-a870.ngrok-free.app/auth/shopify/callback",
  "https://3dcf-2401-4900-1f37-cbfd-1d35-c7a8-c9fb-a870.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
