# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80cd4a853faeec3441d5fada915afdab"
name = "testing-01"
handle = "testing-1542"
application_url = "https://4ea2-122-161-52-231.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_cart_transforms, write_cart_transforms, read_checkout_branding_settings, write_checkout_branding_settings, read_customers, write_customers, read_discounts, write_discounts, read_locations, write_locations, read_orders, write_orders, storefronts"

[auth]
redirect_urls = [
  "https://4ea2-122-161-52-231.ngrok-free.app/auth/callback",
  "https://4ea2-122-161-52-231.ngrok-free.app/auth/shopify/callback",
  "https://4ea2-122-161-52-231.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "quickstart-2425cd3f.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
